-- ============================================================================
-- 007 — General Inventory: tables, constraints, indexes, guard triggers
-- ============================================================================
-- Phase 1 of docs/inventory-design.md (rev 3). Additive only: no existing
-- table is altered; existing tables are only referenced by foreign keys.
--
--   007_inventory_schema.sql     tables + guard triggers            (this file)
--   008_inventory_access.sql     scope/capability helpers, RLS, views
--   009_inventory_engine.sql     posting engine (internal fn_inv_* functions)
--   010_inventory_rpc_stock.sql  stock-movement RPCs
--   011_inventory_rpc_admin.sql  reversal/correction, service charges, periods
--   012_inventory_seed.sql       UOMs, categories, locations, branch settings
--   013_inventory_grants.sql     ALL grants/revokes + read-back (re-run after
--                                every inventory migration)
--
-- Apply in order 007 → 013 in a quiet window. Each file is one transaction and
-- can be re-run.
-- Rollback (pre-go-live only): migration/scripts/rollback_inventory_v1.sql
-- Tests: `npm run test:inventory` in webapp/ (PGlite, never production).
--
-- Conventions (D-10, D-112, D-114):
--   * every name is prefixed tbl_inv_ / fn_inv_ / inv_ / v_inv_
--   * vocabularies are text + CHECK, not enums
--   * every branch-scoped table (children included) carries branch_id
--   * ids are "generated by default" so the engine can pre-allocate them
--   * clients never write: RLS is SELECT-only and grants are SELECT-only
-- ============================================================================

begin;

-- The FKs below take SHARE ROW EXCLUSIVE locks on tbl_branches, tbl_staff,
-- tbl_residents and tbl_user_accounts until COMMIT: fail fast instead of
-- queueing behind (and blocking) app traffic (audit P1-15).
set local lock_timeout = '5s';

-- D-133: SQL detects demo branches with tbl_branches.is_demo, the app with
-- BranchCode = 'DEMO' (getDemoBranchIds). Refuse to install if they differ.
do $$
begin
  if exists (
    select 1 from public.tbl_branches b
    where b.is_demo is distinct from (b."BranchCode" = 'DEMO')
  ) then
    raise exception 'INV_INSTALL: tbl_branches.is_demo does not match BranchCode = ''DEMO'' (D-133)';
  end if;
end $$;

-- ----------------------------------------------------------------------------
-- 1. Master data (org-wide; owner_branch_id is only ever a demo branch, D-102)
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_uoms (
  id              bigint generated by default as identity primary key,
  code            text not null unique check (code ~ '^[A-Z0-9_]{1,12}$'),
  name            text not null check (length(btrim(name)) between 1 and 60),
  name_ms         text check (length(name_ms) <= 60),
  allow_fraction  boolean not null default false,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now()
);

-- D-137: is_service marks the one non-stock category (Service).
create table if not exists public.tbl_inv_categories (
  id          bigint generated by default as identity primary key,
  code        text not null unique check (code ~ '^[A-Z0-9_]{1,24}$'),
  name        text not null check (length(btrim(name)) between 1 and 60),
  name_ms     text check (length(name_ms) <= 60),
  is_service  boolean not null default false,
  sort_order  int not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.tbl_inv_suppliers (
  id                  bigint generated by default as identity primary key,
  owner_branch_id     bigint references public.tbl_branches ("BranchID"),   -- NULL = global (D-102)
  name                text not null check (length(btrim(name)) between 1 and 120),
  name_key            text generated always as (lower(regexp_replace(btrim(name), '\s+', ' ', 'g'))) stored,
  contact_person      text check (length(contact_person) <= 120),
  phone               text check (length(phone) <= 40),
  email               text check (length(email) <= 120),
  address             text check (length(address) <= 400),
  notes               text check (length(notes) <= 500),
  is_active           boolean not null default true,
  created_by_account  bigint not null references public.tbl_user_accounts (id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  updated_by_account  bigint references public.tbl_user_accounts (id)
);
create unique index if not exists uq_inv_suppliers_name
  on public.tbl_inv_suppliers (coalesce(owner_branch_id, 0), name_key);

-- D-136: no goods_class — Inventory is the only stock/billing system for
-- OSEM-bought goods. D-137: is_stock_item = NOT category.is_service.
create table if not exists public.tbl_inv_products (
  id                   bigint generated by default as identity primary key,
  owner_branch_id      bigint references public.tbl_branches ("BranchID"),  -- NULL = global; demo only
  sku                  text not null check (sku ~ '^[A-Za-z0-9._-]{1,40}$'),
  name                 text not null check (length(btrim(name)) between 1 and 160),
  description          text check (length(description) <= 1000),
  category_id          bigint not null references public.tbl_inv_categories (id),
  is_stock_item        boolean not null default true,
  base_uom_id          bigint not null references public.tbl_inv_uoms (id),   -- immutable once used (D-106)
  purchase_uom_id      bigint not null references public.tbl_inv_uoms (id),
  default_supplier_id  bigint references public.tbl_inv_suppliers (id),
  standard_unit_cost   numeric(18,6) check (standard_unit_cost between 0 and 100000),  -- per base; fallback only
  is_chargeable        boolean not null default true,                        -- false: RESIDENT charge blocked (D-121)
  charge_price         numeric(12,4) check (charge_price between 0 and 100000),        -- per base; NULL → PRICE_PENDING
  default_max_store    numeric(18,4) check (default_max_store >= 0),         -- D-101
  default_max_floor    numeric(18,4) check (default_max_floor >= 0),
  is_active            boolean not null default true,
  created_by_account   bigint not null references public.tbl_user_accounts (id),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  updated_by_account   bigint references public.tbl_user_accounts (id),
  check (is_stock_item or (default_max_store is null and default_max_floor is null))
);
create unique index if not exists uq_inv_products_sku
  on public.tbl_inv_products (coalesce(owner_branch_id, 0), sku);
create index if not exists idx_inv_products_name_trgm
  on public.tbl_inv_products using gin (name public.gin_trgm_ops);
create index if not exists idx_inv_products_category on public.tbl_inv_products (category_id);

create table if not exists public.tbl_inv_product_uoms (
  product_id      bigint not null references public.tbl_inv_products (id),
  uom_id          bigint not null references public.tbl_inv_uoms (id),
  factor_to_base  numeric(18,6) not null check (factor_to_base >= 1),   -- base = smallest issuable unit (D-106)
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  primary key (product_id, uom_id)
);

create table if not exists public.tbl_inv_product_barcodes (
  id                  bigint generated by default as identity primary key,
  barcode             text not null check (barcode ~ '^[\x21-\x7E]{3,64}$'),
  product_id          bigint not null,
  uom_id              bigint not null,
  owner_branch_id     bigint references public.tbl_branches ("BranchID"),   -- copied from the product
  is_active           boolean not null default true,
  created_by_account  bigint not null references public.tbl_user_accounts (id),
  created_at          timestamptz not null default now(),
  foreign key (product_id, uom_id) references public.tbl_inv_product_uoms (product_id, uom_id)
);
create unique index if not exists uq_inv_barcode_active
  on public.tbl_inv_product_barcodes (coalesce(owner_branch_id, 0), barcode) where is_active;   -- D-128
create index if not exists idx_inv_barcodes_product on public.tbl_inv_product_barcodes (product_id, uom_id);

-- ----------------------------------------------------------------------------
-- 2. Branch settings, locations, stock levels, billing codes
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_branch_settings (
  branch_id                    bigint primary key references public.tbl_branches ("BranchID"),
  is_enabled                   boolean not null default false,
  go_live_date                 date,
  opening_window_days          int not null default 7 check (opening_window_days between 0 and 31),   -- D-117
  writeoff_threshold           numeric(12,2) not null default 50.00 check (writeoff_threshold >= 0), -- D-108, Q-7
  osem_issue_review_threshold  numeric(12,2) not null default 100.00 check (osem_issue_review_threshold >= 0),
  created_at                   timestamptz not null default now(),
  updated_at                   timestamptz not null default now(),
  updated_by_account           bigint references public.tbl_user_accounts (id),
  check (not is_enabled or go_live_date is not null)
);

-- D-20/D-140: exactly one STORE, FLOOR, TRANSIT per NUR branch (guard trigger).
create table if not exists public.tbl_inv_locations (
  id                    bigint generated by default as identity primary key,
  branch_id             bigint not null references public.tbl_branches ("BranchID"),
  kind                  text not null check (kind in ('STORE','FLOOR','TRANSIT')),
  name                  text not null check (length(btrim(name)) between 1 and 60),
  count_frequency_days  int check (count_frequency_days > 0),
  is_active             boolean not null default true,
  created_at            timestamptz not null default now(),
  unique (branch_id, kind)
);

create table if not exists public.tbl_inv_stock_levels (   -- per-location override of product defaults (D-101)
  location_id         bigint not null references public.tbl_inv_locations (id),
  product_id          bigint not null references public.tbl_inv_products (id),
  branch_id           bigint not null references public.tbl_branches ("BranchID"),
  max_qty             numeric(18,4) not null check (max_qty >= 0),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  updated_by_account  bigint not null references public.tbl_user_accounts (id),
  primary key (location_id, product_id)
);
create index if not exists idx_inv_stock_levels_branch on public.tbl_inv_stock_levels (branch_id, product_id);

create table if not exists public.tbl_inv_resident_billing (   -- D-122
  resident_id         bigint primary key references public.tbl_residents (id),
  branch_id           bigint not null references public.tbl_branches ("BranchID"),
  billing_code        text not null unique check (length(btrim(billing_code)) between 1 and 40),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  updated_by_account  bigint not null references public.tbl_user_accounts (id)
);
create index if not exists idx_inv_resident_billing_branch on public.tbl_inv_resident_billing (branch_id);

-- ----------------------------------------------------------------------------
-- 3. Periods, closing snapshots, counters, idempotency
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_billing_periods (
  id                              bigint generated by default as identity primary key,
  branch_id                       bigint not null references public.tbl_branches ("BranchID"),
  period_month                    date not null check (period_month = date_trunc('month', period_month)::date),
  status                          text not null default 'OPEN' check (status in ('OPEN','LOCKED')),
  exceptions_reviewed_at          timestamptz,
  exceptions_reviewed_by_account  bigint references public.tbl_user_accounts (id),
  exceptions_reviewed_by_staff    text references public.tbl_staff ("StaffID"),
  locked_at                       timestamptz,
  locked_by_account               bigint references public.tbl_user_accounts (id),
  locked_by_staff                 text references public.tbl_staff ("StaffID"),
  reopen_count                    int not null default 0 check (reopen_count >= 0),
  created_at                      timestamptz not null default now(),
  unique (branch_id, period_month),
  check ((status = 'LOCKED') = (locked_at is not null))
);

create table if not exists public.tbl_inv_period_closing (   -- D-116; append-only, one set per lock
  billing_period_id  bigint not null references public.tbl_inv_billing_periods (id),
  branch_id          bigint not null references public.tbl_branches ("BranchID"),
  lock_seq           int not null,
  product_id         bigint not null references public.tbl_inv_products (id),
  location_id        bigint references public.tbl_inv_locations (id),   -- NULL row = pool total
  resident_id        bigint references public.tbl_residents (id),
  qty                numeric(18,4) not null,
  value              numeric(18,4),                                     -- pool and in-transit rows only
  in_transit_transfer_id bigint,   -- set: goods dispatched to another branch, not received by month end (D-153)
  created_at         timestamptz not null default now(),
  check ((location_id is null) = (value is not null))
);
create unique index if not exists uq_inv_period_closing on public.tbl_inv_period_closing
  (billing_period_id, lock_seq, product_id, location_id, resident_id, in_transit_transfer_id) nulls not distinct;
create index if not exists idx_inv_period_closing_branch on public.tbl_inv_period_closing (branch_id, billing_period_id);

create table if not exists public.tbl_inv_counters (
  branch_id   bigint not null references public.tbl_branches ("BranchID"),
  doc_type    text not null check (doc_type in ('TXN','RCV','TRF','REQ','CNT','ADJ','EXP')),
  year        int not null check (year between 2000 and 2999),   -- KL year of posting (D-129)
  last_no     int not null default 0 check (last_no >= 0),
  primary key (branch_id, doc_type, year)
);  -- number format <BranchCode>-<DOC>-<YYYY>-<000123>

create table if not exists public.tbl_inv_idempotency (   -- D-110
  key           uuid primary key,
  rpc           text not null,
  account_id    bigint not null references public.tbl_user_accounts (id),
  request_hash  bytea not null,
  result        jsonb not null,
  created_at    timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 4. Ledger (source of truth)
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_txns (
  id                           bigint generated by default as identity primary key,
  txn_no                       text not null unique,
  txn_type                     text not null check (txn_type in (
    'OPENING_BALANCE','RECEIPT','ISSUE','INTERNAL_TRANSFER','TRANSIT_ALLOCATE','TRANSIT_RELEASE',
    'BRANCH_TRANSFER_OUT','BRANCH_TRANSFER_IN','RETURN_FROM_ISSUE','RETURN_TO_SUPPLIER',
    'DAMAGED_EXPIRED','ADJUSTMENT','REVERSAL')),
  branch_id                    bigint not null references public.tbl_branches ("BranchID"),
  txn_date                     date not null,                                   -- KL business date
  billing_period_id            bigint not null references public.tbl_inv_billing_periods (id),
  posted_at                    timestamptz not null default clock_timestamp(),
  performed_by_staff           text not null references public.tbl_staff ("StaffID"),
  posted_by_account            bigint not null references public.tbl_user_accounts (id),
  approved_by_account          bigint references public.tbl_user_accounts (id),
  approved_by_staff            text references public.tbl_staff ("StaffID"),
  reason_code                  text check (reason_code in ('DAMAGED','EXPIRED','COUNT_VARIANCE','FOUND','LOST',
    'TRANSFER_DISCREPANCY','DATA_ENTRY','WRONG_RESIDENT','WRONG_PRODUCT','WRONG_QTY','WRONG_COST','DISCHARGED',
    'DECEASED','NO_LONGER_REQUIRED','WRONG_ALLOCATION','OTHER')),
  remarks                      text check (length(remarks) <= 500),
  expense_note                 text check (length(expense_note) <= 200),       -- OSEM-expense issues (Q-19)
  negative_stock_confirmed     boolean not null default false,
  inactive_resident_confirmed  boolean not null default false,
  sanity_confirmed             boolean not null default false,                 -- D-109
  reverses_txn_id              bigint unique references public.tbl_inv_txns (id),
  correction_of_txn_id         bigint references public.tbl_inv_txns (id),
  cascade_of_txn_id            bigint references public.tbl_inv_txns (id),     -- D-124
  source_doc_type              text check (source_doc_type in ('RECEIPT','BRANCH_TRANSFER','ADJUSTMENT')),
  source_doc_id                bigint,
  request_key                  uuid not null references public.tbl_inv_idempotency (key) deferrable initially deferred,
  created_at                   timestamptz not null default now(),
  check ((txn_type = 'REVERSAL') = (reverses_txn_id is not null)),
  check ((source_doc_type is null) = (source_doc_id is null))
);
create index if not exists idx_inv_txns_branch_date on public.tbl_inv_txns (branch_id, txn_date desc, id desc);
create index if not exists idx_inv_txns_period on public.tbl_inv_txns (billing_period_id);
create index if not exists idx_inv_txns_source on public.tbl_inv_txns (source_doc_type, source_doc_id);
create index if not exists idx_inv_txns_request on public.tbl_inv_txns (request_key);
create index if not exists idx_inv_txns_correction on public.tbl_inv_txns (correction_of_txn_id) where correction_of_txn_id is not null;

create table if not exists public.tbl_inv_txn_lines (
  id                 bigint generated by default as identity primary key,
  txn_id             bigint not null references public.tbl_inv_txns (id) deferrable initially deferred,
  line_no            smallint not null check (line_no > 0),
  branch_id          bigint not null references public.tbl_branches ("BranchID"),
  txn_date           date not null,                                             -- denormalised (D-115)
  txn_type           text not null,                                             -- denormalised
  location_id        bigint not null references public.tbl_inv_locations (id),
  location_kind      text not null check (location_kind in ('STORE','FLOOR','TRANSIT')),
  resident_id        bigint references public.tbl_residents (id),
  product_id         bigint not null references public.tbl_inv_products (id),
  qty_base           numeric(18,4) not null check (qty_base <> 0),
  uom_id             bigint not null references public.tbl_inv_uoms (id),
  uom_code           text not null,
  qty_entered        numeric(18,4) not null check (qty_entered > 0),           -- paid + FOC on receipts
  factor_to_base     numeric(18,6) not null check (factor_to_base >= 1),
  unit_cost          numeric(18,6) not null check (unit_cost >= 0),             -- per base uom
  value              numeric(18,4) not null,
  revaluation_value  numeric(18,4) not null default 0,
  cost_source        text not null check (cost_source in
    ('INPUT','LANDED','WAC','ORIGINAL','TRANSFER','MASTER_FALLBACK','PENDING_COST')),
  bucket_qty_after   numeric(18,4) not null,
  pool_qty_after     numeric(18,4) not null,
  pool_value_after   numeric(18,4) not null,
  pool_wac_after     numeric(18,6),
  pair_line_id       bigint references public.tbl_inv_txn_lines (id) deferrable initially deferred,
  source_line_id     bigint references public.tbl_inv_txn_lines (id) deferrable initially deferred,
  created_at         timestamptz not null default now(),
  unique (txn_id, line_no),
  check ((location_kind = 'TRANSIT') = (resident_id is not null)),
  check (abs(qty_base - sign(qty_base) * qty_entered * factor_to_base) < 0.00005)
);
create index if not exists idx_inv_lines_pool on public.tbl_inv_txn_lines (branch_id, product_id, id);
create index if not exists idx_inv_lines_bucket on public.tbl_inv_txn_lines (location_id, product_id, resident_id, id);
create index if not exists idx_inv_lines_date on public.tbl_inv_txn_lines (branch_id, txn_date, id);
create index if not exists idx_inv_lines_prod_date on public.tbl_inv_txn_lines (branch_id, product_id, txn_date);
create index if not exists idx_inv_lines_txn on public.tbl_inv_txn_lines (txn_id);
create index if not exists idx_inv_lines_source on public.tbl_inv_txn_lines (source_line_id) where source_line_id is not null;
create index if not exists idx_inv_lines_resident on public.tbl_inv_txn_lines (resident_id) where resident_id is not null;
create index if not exists idx_inv_lines_product_uom on public.tbl_inv_txn_lines (product_id, uom_id);

-- ----------------------------------------------------------------------------
-- 5. Balance caches (written only by the engine, GUC inv.posting = 'on')
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_cost_pools (   -- branch × product (D-50, Q-4)
  branch_id     bigint not null references public.tbl_branches ("BranchID"),
  product_id    bigint not null references public.tbl_inv_products (id),
  qty           numeric(18,4) not null default 0,
  value         numeric(18,4) not null default 0,
  wac           numeric(18,6),
  last_line_id  bigint references public.tbl_inv_txn_lines (id),
  updated_at    timestamptz not null default now(),
  primary key (branch_id, product_id)
);

create table if not exists public.tbl_inv_balances (     -- location × product × resident
  id            bigint generated by default as identity primary key,
  branch_id     bigint not null references public.tbl_branches ("BranchID"),
  location_id   bigint not null references public.tbl_inv_locations (id),
  product_id    bigint not null references public.tbl_inv_products (id),
  resident_id   bigint references public.tbl_residents (id),
  qty           numeric(18,4) not null default 0,
  last_line_id  bigint references public.tbl_inv_txn_lines (id),
  updated_at    timestamptz not null default now(),
  constraint uq_inv_balances_bucket unique nulls not distinct (location_id, product_id, resident_id)
);
create index if not exists idx_inv_balances_branch on public.tbl_inv_balances (branch_id, product_id);
create index if not exists idx_inv_balances_resident on public.tbl_inv_balances (resident_id) where resident_id is not null;
create index if not exists idx_inv_balances_negative on public.tbl_inv_balances (branch_id) where qty < 0;

-- ----------------------------------------------------------------------------
-- 6. Documents (workflow state; stock and value live in the ledger, D-14)
-- ----------------------------------------------------------------------------

-- Stock requests (D-100, D-119). Workflow RPCs: Phase 5.
create table if not exists public.tbl_inv_stock_requests (
  id                      bigint generated by default as identity primary key,
  request_no              text not null unique,
  branch_id               bigint not null references public.tbl_branches ("BranchID"),
  status                  text not null check (status in ('DRAFT','SUBMITTED','APPROVED','REJECTED','ORDERED',
                                                           'PARTIALLY_RECEIVED','RECEIVED','CLOSED','CANCELLED')),
  requested_by_staff      text not null references public.tbl_staff ("StaffID"),
  created_by_account      bigint not null references public.tbl_user_accounts (id),
  submitted_at            timestamptz,
  reviewed_by_account     bigint references public.tbl_user_accounts (id),
  reviewed_by_staff       text references public.tbl_staff ("StaffID"),
  reviewed_at             timestamptz,
  review_note             text check (length(review_note) <= 500),
  ordered_at              timestamptz,
  ordered_by_account      bigint references public.tbl_user_accounts (id),
  external_ref            text check (length(external_ref) <= 60),
  expected_delivery_date  date,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  check (reviewed_by_account is null or reviewed_by_account <> created_by_account)   -- D-82
);
create index if not exists idx_inv_stock_requests_branch on public.tbl_inv_stock_requests (branch_id, status);

create table if not exists public.tbl_inv_stock_request_lines (
  id                       bigint generated by default as identity primary key,
  request_id               bigint not null references public.tbl_inv_stock_requests (id),
  branch_id                bigint not null references public.tbl_branches ("BranchID"),
  product_id               bigint not null references public.tbl_inv_products (id),
  supplier_id              bigint references public.tbl_inv_suppliers (id),
  current_qty_snapshot     numeric(18,4) not null,
  max_qty_snapshot         numeric(18,4),
  suggested_qty            numeric(18,4) not null check (suggested_qty >= 0),
  requested_qty            numeric(18,4) not null check (requested_qty > 0),     -- base
  approved_qty             numeric(18,4) check (approved_qty >= 0),
  closed_short_at          timestamptz,
  closed_short_by_account  bigint references public.tbl_user_accounts (id),
  closed_short_reason      text check (length(closed_short_reason) <= 200),
  remarks                  text check (length(remarks) <= 500),
  created_at               timestamptz not null default now(),
  unique (request_id, product_id)
);
create index if not exists idx_inv_request_lines_branch on public.tbl_inv_stock_request_lines (branch_id, product_id);

create table if not exists public.tbl_inv_stock_request_events (   -- append-only
  id          bigint generated by default as identity primary key,
  request_id  bigint not null references public.tbl_inv_stock_requests (id),
  branch_id   bigint not null references public.tbl_branches ("BranchID"),
  event       text not null check (event in ('CREATED','SUBMITTED','APPROVED','REJECTED','ORDERED','FOLLOW_UP',
                                             'RECEIPT_LINKED','LINE_CLOSED_SHORT','CLOSED','CANCELLED')),
  note        text check (length(note) <= 500),
  account_id  bigint not null references public.tbl_user_accounts (id),
  staff_id    text references public.tbl_staff ("StaffID"),
  created_at  timestamptz not null default now()
);
create index if not exists idx_inv_request_events_request on public.tbl_inv_stock_request_events (request_id);

-- Receipts (D-105 as narrowed by D-138: the invoice is mandatory; no DO,
-- no provisional cost, no reconciliation status).
create table if not exists public.tbl_inv_receipts (
  id                        bigint generated by default as identity primary key,
  receipt_no                text not null unique,
  branch_id                 bigint not null references public.tbl_branches ("BranchID"),
  location_id               bigint not null references public.tbl_inv_locations (id),   -- the branch STORE (D-23)
  supplier_id               bigint not null references public.tbl_inv_suppliers (id),
  supplier_name             text not null,
  doc_type                  text not null check (doc_type in ('INVOICE','CASH_BILL')),
  invoice_no                text not null check (length(btrim(invoice_no)) between 1 and 60),
  invoice_key               text generated always as (upper(regexp_replace(invoice_no, '[^A-Za-z0-9]', '', 'g'))) stored,
  invoice_date              date not null,
  received_date             date not null,
  received_by_staff         text not null references public.tbl_staff ("StaffID"),
  item_count                int not null check (item_count > 0),
  lines_total               numeric(14,2) not null check (lines_total >= 0),         -- Σ line_total (paid qty)
  discount_total            numeric(14,2) not null default 0 check (discount_total >= 0),
  tax_total                 numeric(14,2) not null default 0 check (tax_total >= 0),  -- SST: non-recoverable → cost
  other_charges_total       numeric(14,2) not null default 0 check (other_charges_total >= 0),
  rounding_adj              numeric(14,2) not null default 0 check (abs(rounding_adj) <= 1.00),
  landed_total              numeric(14,2) not null check (landed_total >= 0),         -- = what the ledger carries
  invoice_total_paper       numeric(14,2) check (invoice_total_paper >= 0),         -- as printed; information only (D-138, P1-18)
  stock_request_id          bigint references public.tbl_inv_stock_requests (id),
  txn_id                    bigint not null unique references public.tbl_inv_txns (id) deferrable initially deferred,
  corrects_receipt_id       bigint references public.tbl_inv_receipts (id),           -- D-103 correction chain
  is_voided                 boolean not null default false,
  voided_by_txn_id          bigint references public.tbl_inv_txns (id),
  superseded_by_receipt_id  bigint references public.tbl_inv_receipts (id) deferrable initially deferred,
  remarks                   text check (length(remarks) <= 500),
  created_by_account        bigint not null references public.tbl_user_accounts (id),
  created_at                timestamptz not null default now(),
  check (is_voided = (voided_by_txn_id is not null)),
  check (landed_total = lines_total - discount_total + tax_total + other_charges_total + rounding_adj)
);
create unique index if not exists uq_inv_receipts_invoice
  on public.tbl_inv_receipts (supplier_id, invoice_key) where not is_voided;
create index if not exists idx_inv_receipts_branch on public.tbl_inv_receipts (branch_id, received_date desc);

create table if not exists public.tbl_inv_receipt_lines (
  id                    bigint generated by default as identity primary key,
  receipt_id            bigint not null references public.tbl_inv_receipts (id),
  branch_id             bigint not null references public.tbl_branches ("BranchID"),
  line_no               smallint not null check (line_no > 0),
  product_id            bigint not null references public.tbl_inv_products (id),
  product_name          text not null,
  uom_id                bigint not null references public.tbl_inv_uoms (id),
  factor_to_base        numeric(18,6) not null check (factor_to_base >= 1),
  qty_entered           numeric(18,4) not null check (qty_entered >= 0),        -- paid qty
  foc_qty               numeric(18,4) not null default 0 check (foc_qty >= 0),  -- free/bonus, same uom
  qty_base              numeric(18,4) not null check (qty_base > 0),            -- (paid + foc) × factor
  unit_cost_entered     numeric(18,6) not null check (unit_cost_entered >= 0),  -- per entered uom, as invoiced
  line_total            numeric(14,2) not null check (line_total >= 0),         -- round(paid × unit cost, 2)
  landed_value          numeric(18,4) not null check (landed_value >= 0),       -- ledger value (pro-rata)
  request_line_id       bigint references public.tbl_inv_stock_request_lines (id),
  allocate_resident_id  bigint references public.tbl_residents (id),            -- receive & allocate (D-40)
  txn_line_id           bigint not null references public.tbl_inv_txn_lines (id) deferrable initially deferred,
  created_at            timestamptz not null default now(),
  unique (receipt_id, line_no),
  check (qty_entered + foc_qty > 0)
);
create index if not exists idx_inv_receipt_lines_receipt on public.tbl_inv_receipt_lines (receipt_id);
create index if not exists idx_inv_receipt_lines_product on public.tbl_inv_receipt_lines (branch_id, product_id);
create index if not exists idx_inv_receipt_lines_request on public.tbl_inv_receipt_lines (request_line_id) where request_line_id is not null;

-- Counts (D-60, D-104, D-123). Workflow RPCs: Phase 7. Postings already
-- honour freeze_location on an IN_PROGRESS count.
create table if not exists public.tbl_inv_counts (
  id                      bigint generated by default as identity primary key,
  count_no                text not null unique,
  branch_id               bigint not null references public.tbl_branches ("BranchID"),
  location_id             bigint not null references public.tbl_inv_locations (id),
  count_type              text not null check (count_type in ('MONTHLY_STORE','WEEKLY_FLOOR','AD_HOC')),
  status                  text not null check (status in ('DRAFT','IN_PROGRESS','SUBMITTED','INVESTIGATED','CLOSED','CANCELLED')),
  freeze_location         boolean not null default false,
  snapshot_line_id        bigint,                                   -- max(line id) at START
  started_at              timestamptz,
  counted_by_staff        text not null references public.tbl_staff ("StaffID"),
  submitted_at            timestamptz,
  investigated_by_staff   text references public.tbl_staff ("StaffID"),
  investigated_by_account bigint references public.tbl_user_accounts (id),
  investigation_summary   text check (length(investigation_summary) <= 2000),
  closed_at               timestamptz,
  created_by_account      bigint not null references public.tbl_user_accounts (id),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);
create unique index if not exists uq_inv_counts_active on public.tbl_inv_counts (location_id) where status = 'IN_PROGRESS';
create index if not exists idx_inv_counts_branch on public.tbl_inv_counts (branch_id, status);

create table if not exists public.tbl_inv_count_lines (
  id                  bigint generated by default as identity primary key,
  count_id            bigint not null references public.tbl_inv_counts (id),
  branch_id           bigint not null references public.tbl_branches ("BranchID"),
  product_id          bigint not null references public.tbl_inv_products (id),
  resident_id         bigint references public.tbl_residents (id),
  is_found_item       boolean not null default false,
  expected_qty        numeric(18,4),
  posted_since_start  numeric(18,4),
  physical_qty        numeric(18,4) check (physical_qty >= 0),
  variance_qty        numeric(18,4) generated always as (physical_qty - expected_qty) stored,
  investigation_note  text check (length(investigation_note) <= 500),
  created_at          timestamptz not null default now()
);
create unique index if not exists uq_inv_count_lines on public.tbl_inv_count_lines (count_id, product_id, resident_id) nulls not distinct;

-- Branch transfers (D-31…D-33, D-113; Q-3: dispatch, then receive all-or-nothing)
create table if not exists public.tbl_inv_branch_transfers (
  id                   bigint generated by default as identity primary key,
  transfer_no          text not null unique,
  from_branch_id       bigint not null references public.tbl_branches ("BranchID"),
  from_location_id     bigint not null references public.tbl_inv_locations (id),
  to_branch_id         bigint not null references public.tbl_branches ("BranchID"),
  to_location_id       bigint not null references public.tbl_inv_locations (id),   -- destination STORE
  status               text not null check (status in ('DISPATCHED','RECEIVED','CANCELLED')),
  dispatch_txn_id      bigint not null unique references public.tbl_inv_txns (id) deferrable initially deferred,
  cancel_txn_id        bigint unique references public.tbl_inv_txns (id),
  dispatched_by_staff  text not null references public.tbl_staff ("StaffID"),
  remarks              text check (length(remarks) <= 500),
  created_by_account   bigint not null references public.tbl_user_accounts (id),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  check (from_branch_id <> to_branch_id),
  check ((status = 'CANCELLED') = (cancel_txn_id is not null))
);
create index if not exists idx_inv_transfers_from on public.tbl_inv_branch_transfers (from_branch_id, status);
create index if not exists idx_inv_transfers_to on public.tbl_inv_branch_transfers (to_branch_id, status);

create table if not exists public.tbl_inv_branch_transfer_lines (
  id           bigint generated by default as identity primary key,
  transfer_id  bigint not null references public.tbl_inv_branch_transfers (id),
  branch_id    bigint not null references public.tbl_branches ("BranchID"),   -- = from_branch_id
  line_no      smallint not null check (line_no > 0),
  product_id   bigint not null references public.tbl_inv_products (id),
  qty_base     numeric(18,4) not null check (qty_base > 0),
  unit_cost    numeric(18,6) not null check (unit_cost >= 0),
  value        numeric(18,4) not null,
  out_line_id  bigint not null references public.tbl_inv_txn_lines (id) deferrable initially deferred,
  created_at   timestamptz not null default now(),
  unique (transfer_id, line_no)
);

-- Adjustments (D-61). Workflow RPCs: Phase 7.
create table if not exists public.tbl_inv_adjustments (
  id                    bigint generated by default as identity primary key,
  adjustment_no         text not null unique,
  branch_id             bigint not null references public.tbl_branches ("BranchID"),
  location_id           bigint not null references public.tbl_inv_locations (id),
  count_id              bigint references public.tbl_inv_counts (id),
  branch_transfer_id    bigint references public.tbl_inv_branch_transfers (id),   -- D-33
  status                text not null check (status in ('PENDING','APPROVED','REJECTED','CANCELLED')),
  reason_code           text not null check (reason_code in ('DAMAGED','EXPIRED','COUNT_VARIANCE','FOUND','LOST',
                          'TRANSFER_DISCREPANCY','DATA_ENTRY','OTHER')),
  justification         text not null check (length(btrim(justification)) between 5 and 1000),
  requested_by_staff    text not null references public.tbl_staff ("StaffID"),
  requested_by_account  bigint not null references public.tbl_user_accounts (id),
  decided_by_staff      text references public.tbl_staff ("StaffID"),
  decided_by_account    bigint references public.tbl_user_accounts (id),
  decided_at            timestamptz,
  decision_note         text check (length(decision_note) <= 500),
  txn_id                bigint unique references public.tbl_inv_txns (id),
  created_at            timestamptz not null default now(),
  check (decided_by_account is null or decided_by_account <> requested_by_account),   -- D-82
  check ((status = 'APPROVED') = (txn_id is not null))
);
create index if not exists idx_inv_adjustments_branch on public.tbl_inv_adjustments (branch_id, status);

create table if not exists public.tbl_inv_adjustment_lines (
  id              bigint generated by default as identity primary key,
  adjustment_id   bigint not null references public.tbl_inv_adjustments (id),
  branch_id       bigint not null references public.tbl_branches ("BranchID"),
  product_id      bigint not null references public.tbl_inv_products (id),
  resident_id     bigint references public.tbl_residents (id),
  qty_delta_base  numeric(18,4) not null check (qty_delta_base <> 0),
  count_line_id   bigint references public.tbl_inv_count_lines (id),
  created_at      timestamptz not null default now()
);
create index if not exists idx_inv_adjustment_lines_adj on public.tbl_inv_adjustment_lines (adjustment_id);

create table if not exists public.tbl_inv_branch_transfer_receipts (   -- append-only; one row per receive
  id                         bigint generated by default as identity primary key,
  transfer_id                bigint not null references public.tbl_inv_branch_transfers (id),
  branch_id                  bigint not null references public.tbl_branches ("BranchID"),   -- = to_branch_id
  receive_txn_id             bigint not null unique references public.tbl_inv_txns (id) deferrable initially deferred,
  received_by_staff          text not null references public.tbl_staff ("StaffID"),
  discrepancy_adjustment_id  bigint references public.tbl_inv_adjustments (id),
  created_at                 timestamptz not null default now()
);
create index if not exists idx_inv_transfer_receipts_transfer on public.tbl_inv_branch_transfer_receipts (transfer_id);

-- ----------------------------------------------------------------------------
-- 7. Charges and exports (D-70, D-121, D-122, D-137)
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_charges (
  id                  bigint generated by default as identity primary key,
  branch_id           bigint not null references public.tbl_branches ("BranchID"),
  billing_period_id   bigint not null references public.tbl_inv_billing_periods (id),
  charge_date         date not null,
  charge_kind         text not null check (charge_kind in
    ('ISSUE','SERVICE','RETURN_CREDIT','REVERSAL','PRICING','MANUAL_ADJUSTMENT')),
  target              text not null check (target in ('RESIDENT','OSEM_EXPENSE')),
  resident_id         bigint references public.tbl_residents (id),
  expense_note        text check (length(expense_note) <= 200),
  txn_id              bigint references public.tbl_inv_txns (id),
  txn_line_id         bigint references public.tbl_inv_txn_lines (id),
  related_charge_id   bigint references public.tbl_inv_charges (id),
  product_id          bigint references public.tbl_inv_products (id),
  product_name        text not null,
  sku                 text not null,
  uom_code            text not null,
  qty_base            numeric(18,4) not null,              -- signed; 0 for PRICING/MANUAL_ADJUSTMENT
  unit_charge_price   numeric(12,4) check (unit_charge_price >= 0),   -- NULL = PRICE_PENDING (resident) / expense
  charge_amount       numeric(12,2) not null,              -- signed; 0 for OSEM_EXPENSE
  cost_amount         numeric(18,4) not null,              -- signed
  reason              text check (length(reason) <= 500),
  request_key         uuid not null references public.tbl_inv_idempotency (key) deferrable initially deferred,
  created_by_account  bigint not null references public.tbl_user_accounts (id),
  created_by_staff    text not null references public.tbl_staff ("StaffID"),
  created_at          timestamptz not null default clock_timestamp(),   -- clock time: the review watermark (D-151)
  check ((target = 'RESIDENT') = (resident_id is not null)),
  check (target = 'RESIDENT' or charge_amount = 0),
  check (charge_kind not in ('ISSUE','RETURN_CREDIT') or txn_line_id is not null),
  check (charge_kind not in ('SERVICE','PRICING','MANUAL_ADJUSTMENT') or txn_line_id is null),
  check (charge_kind in ('ISSUE','SERVICE') or related_charge_id is not null),
  check (charge_kind not in ('ISSUE','SERVICE') or (related_charge_id is null and product_id is not null)),
  check (charge_kind <> 'PRICING' or reason is not null),
  check ((txn_id is null) = (txn_line_id is null))
);
create unique index if not exists uq_inv_charges_line on public.tbl_inv_charges (txn_line_id) where txn_line_id is not null;
create unique index if not exists uq_inv_charges_pricing on public.tbl_inv_charges (related_charge_id) where charge_kind = 'PRICING';
create unique index if not exists uq_inv_charges_reversal on public.tbl_inv_charges (related_charge_id) where charge_kind = 'REVERSAL';
create index if not exists idx_inv_charges_period on public.tbl_inv_charges (branch_id, billing_period_id);
create index if not exists idx_inv_charges_resident on public.tbl_inv_charges (resident_id, charge_date desc);
create index if not exists idx_inv_charges_related on public.tbl_inv_charges (related_charge_id) where related_charge_id is not null;
create index if not exists idx_inv_charges_txn on public.tbl_inv_charges (txn_id) where txn_id is not null;

create table if not exists public.tbl_inv_charge_exports (   -- D-122; Phase 8
  id                   bigint generated by default as identity primary key,
  export_no            text not null unique,
  branch_id            bigint not null references public.tbl_branches ("BranchID"),
  billing_period_id    bigint not null references public.tbl_inv_billing_periods (id),
  layout               text not null check (layout in ('ITEMISED','SUMMARY')),
  exported_by_account  bigint not null references public.tbl_user_accounts (id),
  row_count            int not null check (row_count >= 0),
  total_amount         numeric(14,2) not null,
  file_sha256          bytea not null,
  created_at           timestamptz not null default now()
);

create table if not exists public.tbl_inv_charge_export_items (   -- append-only
  export_id   bigint not null references public.tbl_inv_charge_exports (id),
  charge_id   bigint not null references public.tbl_inv_charges (id),
  branch_id   bigint not null references public.tbl_branches ("BranchID"),
  created_at  timestamptz not null default now(),
  primary key (export_id, charge_id)
);

-- ----------------------------------------------------------------------------
-- 8. Audit (D-90). One semantic event per business action, written by RPCs.
-- ----------------------------------------------------------------------------

create table if not exists public.tbl_inv_audit_log (
  id               bigint generated by default as identity primary key,
  occurred_at      timestamptz not null default clock_timestamp(),
  action           text not null check (length(action) between 1 and 60),
  entity           text not null check (length(entity) between 1 and 60),
  entity_id        text not null,
  branch_id        bigint references public.tbl_branches ("BranchID"),   -- NULL for global master data
  owner_branch_id  bigint references public.tbl_branches ("BranchID"),   -- demo-owned master data
  account_id       bigint references public.tbl_user_accounts (id),      -- NULL only for postgres maintenance
  auth_user_id     uuid,
  db_user          text not null default session_user,
  staff_id         text references public.tbl_staff ("StaffID"),
  txn_id           bigint references public.tbl_inv_txns (id),
  request_key      uuid,
  reason           text check (length(reason) <= 500),
  before_data      jsonb,
  after_data       jsonb
);
create index if not exists idx_inv_audit_entity on public.tbl_inv_audit_log (entity, entity_id, occurred_at desc);
create index if not exists idx_inv_audit_branch on public.tbl_inv_audit_log (branch_id, occurred_at desc);

-- ============================================================================
-- 9. Guard triggers (D-19, D-106, D-128, D-140, D-144)
-- ============================================================================

-- True only inside fn_inv_purge_demo() run from the SQL editor (D-126, Q-21).
create or replace function public.fn_inv_purge_allowed(p_row jsonb) returns boolean
language plpgsql stable set search_path = '' as $$
declare
  v_branch bigint;
begin
  if coalesce(current_setting('inv.demo_purge', true), '') <> 'on' or session_user <> 'postgres' then
    return false;
  end if;
  v_branch := coalesce((p_row->>'branch_id')::bigint, (p_row->>'from_branch_id')::bigint,
    (p_row->>'owner_branch_id')::bigint,
    (select a.branch_id from public.tbl_user_accounts a where a.id = (p_row->>'account_id')::bigint),
    (select p.owner_branch_id from public.tbl_inv_products p where p.id = (p_row->>'product_id')::bigint));
  return v_branch is not null
     and exists (select 1 from public.tbl_branches b where b."BranchID" = v_branch and b.is_demo);
end $$;

-- Append-only tables: no UPDATE, no DELETE (except the demo purge).
create or replace function public.fn_inv_block_mutation() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' and public.fn_inv_purge_allowed(to_jsonb(old)) then
    return old;
  end if;
  raise exception 'INV_IMMUTABLE: % on % is not allowed', tg_op, tg_table_name using errcode = 'P0001';
end $$;

create or replace function public.fn_inv_block_truncate() returns trigger
language plpgsql set search_path = '' as $$
begin
  raise exception 'INV_IMMUTABLE: TRUNCATE on % is not allowed', tg_table_name using errcode = 'P0001';
end $$;

-- Caches and counters: only the engine (inv.posting / inv.rebuild) writes.
create or replace function public.fn_inv_guard_cache() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' and public.fn_inv_purge_allowed(to_jsonb(old)) then
    return old;
  end if;
  if coalesce(current_setting('inv.posting', true), '') = 'on'
     or (coalesce(current_setting('inv.rebuild', true), '') = 'on' and session_user = 'postgres') then
    if tg_op = 'DELETE' then
      raise exception 'INV_IMMUTABLE: DELETE on % is not allowed', tg_table_name using errcode = 'P0001';
    end if;
    return new;
  end if;
  raise exception 'INV_ENGINE_ONLY: % on % is only allowed inside the posting engine', tg_op, tg_table_name
    using errcode = 'P0001';
end $$;

-- Master data: never deleted (deactivate instead).
create or replace function public.fn_inv_block_delete() returns trigger
language plpgsql set search_path = '' as $$
begin
  if public.fn_inv_purge_allowed(to_jsonb(old)) then
    return old;
  end if;
  raise exception 'INV_IMMUTABLE: DELETE on % is not allowed (deactivate instead)', tg_table_name
    using errcode = 'P0001';
end $$;

-- Document tables: UPDATE only inside the engine and only through an explicit
-- per-table whitelist of columns and status transitions (D-144, F12).
create or replace function public.fn_inv_guard_document() returns trigger
language plpgsql set search_path = '' as $$
declare
  v_old jsonb := to_jsonb(old);
  v_new jsonb;
  v_changed text[];
  v_allowed text[];
  v_from text;
  v_to text;
  v_ok boolean := true;
begin
  if tg_op = 'DELETE' then
    if public.fn_inv_purge_allowed(v_old) then
      return old;
    end if;
    raise exception 'INV_IMMUTABLE: DELETE on % is not allowed', tg_table_name using errcode = 'P0001';
  end if;

  if coalesce(current_setting('inv.posting', true), '') <> 'on' then
    raise exception 'INV_ENGINE_ONLY: UPDATE on % is only allowed inside the posting engine', tg_table_name
      using errcode = 'P0001';
  end if;

  v_new := to_jsonb(new);
  -- generated columns are not yet computed in a BEFORE trigger: ignore them
  select coalesce(array_agg(k), '{}') into v_changed
    from jsonb_object_keys(v_new) k
   where v_new->k is distinct from v_old->k
     and k not in (select a.attname from pg_catalog.pg_attribute a
                    where a.attrelid = tg_relid and a.attgenerated <> '');
  v_from := v_old->>'status';
  v_to := v_new->>'status';

  case tg_table_name
    when 'tbl_inv_receipts' then
      v_allowed := array['is_voided','voided_by_txn_id','superseded_by_receipt_id'];
      v_ok := (not ('is_voided' = any(v_changed)) or (v_old->>'is_voided')::boolean = false)
          and (not ('voided_by_txn_id' = any(v_changed)) or v_old->'voided_by_txn_id' = 'null'::jsonb)
          and (not ('superseded_by_receipt_id' = any(v_changed)) or v_old->'superseded_by_receipt_id' = 'null'::jsonb);
    when 'tbl_inv_branch_transfers' then
      v_allowed := array['status','cancel_txn_id','updated_at'];
      v_ok := (v_from = v_to or (v_from, v_to) in (('DISPATCHED','RECEIVED'),('RECEIVED','DISPATCHED'),('DISPATCHED','CANCELLED')))
          and (not ('cancel_txn_id' = any(v_changed)) or (v_old->'cancel_txn_id' = 'null'::jsonb and v_to = 'CANCELLED'));
    when 'tbl_inv_billing_periods' then
      v_allowed := array['status','exceptions_reviewed_at','exceptions_reviewed_by_account','exceptions_reviewed_by_staff',
                         'locked_at','locked_by_account','locked_by_staff','reopen_count'];
      v_ok := case
        when v_from = 'LOCKED' and v_to = 'OPEN' then (v_new->>'reopen_count')::int = (v_old->>'reopen_count')::int + 1
        else (v_new->>'reopen_count')::int = (v_old->>'reopen_count')::int
             and (v_from = v_to or (v_from = 'OPEN' and v_to = 'LOCKED'))
             and (v_from = 'OPEN' or not (array['exceptions_reviewed_at'] <@ v_changed))
      end;
    when 'tbl_inv_stock_requests' then
      v_allowed := array['status','submitted_at','reviewed_by_account','reviewed_by_staff','reviewed_at','review_note',
                         'ordered_at','ordered_by_account','external_ref','expected_delivery_date','updated_at'];
      v_ok := v_from = v_to or (v_from, v_to) in (
        ('DRAFT','SUBMITTED'),('DRAFT','CANCELLED'),('SUBMITTED','APPROVED'),('SUBMITTED','REJECTED'),
        ('SUBMITTED','CANCELLED'),('APPROVED','ORDERED'),('APPROVED','CANCELLED'),('APPROVED','CLOSED'),
        ('ORDERED','PARTIALLY_RECEIVED'),('ORDERED','RECEIVED'),('ORDERED','CLOSED'),
        ('PARTIALLY_RECEIVED','RECEIVED'),('PARTIALLY_RECEIVED','CLOSED'));
    when 'tbl_inv_stock_request_lines' then
      v_allowed := array['approved_qty','requested_qty','supplier_id','remarks',
                         'closed_short_at','closed_short_by_account','closed_short_reason'];
      v_ok := not ('closed_short_at' = any(v_changed)) or v_old->'closed_short_at' = 'null'::jsonb;
    when 'tbl_inv_counts' then
      v_allowed := array['status','freeze_location','snapshot_line_id','started_at','submitted_at','investigated_by_staff',
                         'investigated_by_account','investigation_summary','closed_at','updated_at'];
      v_ok := (v_from = v_to or (v_from, v_to) in (
                 ('DRAFT','IN_PROGRESS'),('DRAFT','CANCELLED'),('IN_PROGRESS','SUBMITTED'),('IN_PROGRESS','CANCELLED'),
                 ('SUBMITTED','INVESTIGATED'),('SUBMITTED','CLOSED'),('SUBMITTED','CANCELLED'),('INVESTIGATED','CLOSED')))
          and (not ('snapshot_line_id' = any(v_changed)) or v_old->'snapshot_line_id' = 'null'::jsonb);
    when 'tbl_inv_count_lines' then
      v_allowed := array['expected_qty','posted_since_start','physical_qty','investigation_note'];
      v_ok := (not ('expected_qty' = any(v_changed)) or v_old->'expected_qty' = 'null'::jsonb)
          and (not ('posted_since_start' = any(v_changed)) or v_old->'posted_since_start' = 'null'::jsonb);
    when 'tbl_inv_adjustments' then
      v_allowed := array['status','decided_by_staff','decided_by_account','decided_at','decision_note','txn_id'];
      v_ok := v_from = 'PENDING' and v_to in ('APPROVED','REJECTED','CANCELLED');
    when 'tbl_inv_adjustment_lines' then
      v_allowed := array['qty_delta_base','count_line_id'];
      v_ok := exists (select 1 from public.tbl_inv_adjustments a
                      where a.id = (v_old->>'adjustment_id')::bigint and a.status = 'PENDING');
    else
      v_allowed := '{}';
      v_ok := false;
  end case;

  if not (v_changed <@ v_allowed) or not coalesce(v_ok, false) then
    raise exception 'INV_TRANSITION: UPDATE of % (%) is not an allowed transition', tg_table_name,
      array_to_string(v_changed, ',') using errcode = 'P0001';
  end if;
  return new;
end $$;

-- D-102, D-106, D-137: product invariants.
create or replace function public.fn_inv_guard_products() returns trigger
language plpgsql set search_path = '' as $$
declare
  v_is_service boolean;
  v_used boolean;
begin
  if new.owner_branch_id is not null
     and not exists (select 1 from public.tbl_branches b where b."BranchID" = new.owner_branch_id and b.is_demo) then
    raise exception 'INV_MASTER: owner_branch_id must be NULL or a demo branch (D-102)' using errcode = 'P0001';
  end if;
  if new.default_supplier_id is not null and not exists (
       select 1 from public.tbl_inv_suppliers s where s.id = new.default_supplier_id
       and (s.owner_branch_id is null or s.owner_branch_id = new.owner_branch_id)) then
    raise exception 'INV_MASTER: default supplier must be global or owned by the same demo branch' using errcode = 'P0001';
  end if;
  select c.is_service into v_is_service from public.tbl_inv_categories c where c.id = new.category_id;
  if new.is_stock_item = coalesce(v_is_service, false) then
    raise exception 'INV_MASTER: is_stock_item must be the opposite of category.is_service (D-137)' using errcode = 'P0001';
  end if;
  if tg_op = 'UPDATE' then
    if new.owner_branch_id is distinct from old.owner_branch_id then
      raise exception 'INV_MASTER: owner_branch_id cannot change' using errcode = 'P0001';
    end if;
    if new.base_uom_id <> old.base_uom_id or new.is_stock_item <> old.is_stock_item then
      v_used := exists (select 1 from public.tbl_inv_txn_lines l where l.product_id = old.id)
             or exists (select 1 from public.tbl_inv_receipt_lines r where r.product_id = old.id)
             or exists (select 1 from public.tbl_inv_charges c where c.product_id = old.id);
      if v_used then
        raise exception 'INV_MASTER: base UOM / stock-item flag cannot change once the product is used (D-106)'
          using errcode = 'P0001';
      end if;
    end if;
  end if;
  return new;
end $$;

-- D-106: factor_to_base is immutable once the (product, uom) is used.
create or replace function public.fn_inv_guard_product_uoms() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.product_id <> old.product_id or new.uom_id <> old.uom_id then
    raise exception 'INV_MASTER: product/uom of a conversion cannot change' using errcode = 'P0001';
  end if;
  if new.factor_to_base <> old.factor_to_base and (
       exists (select 1 from public.tbl_inv_txn_lines l where l.product_id = old.product_id and l.uom_id = old.uom_id)
    or exists (select 1 from public.tbl_inv_receipt_lines r where r.product_id = old.product_id and r.uom_id = old.uom_id)
    or exists (select 1 from public.tbl_inv_product_barcodes b where b.product_id = old.product_id and b.uom_id = old.uom_id)) then
    raise exception 'INV_MASTER: factor_to_base cannot change once used; add a new UOM instead (D-106)'
      using errcode = 'P0001';
  end if;
  return new;
end $$;

-- Deferred: the base row exists with factor 1, the purchase row exists, and
-- only the base row has factor 1 (D-106).
create or replace function public.fn_inv_check_product_uoms() returns trigger
language plpgsql set search_path = '' as $$
declare
  v_product bigint := case when tg_table_name = 'tbl_inv_products' then (to_jsonb(new)->>'id')::bigint
                           else (to_jsonb(new)->>'product_id')::bigint end;
  v_base bigint;
  v_purchase bigint;
begin
  select p.base_uom_id, p.purchase_uom_id into v_base, v_purchase from public.tbl_inv_products p where p.id = v_product;
  if not found then
    return null;
  end if;
  if not exists (select 1 from public.tbl_inv_product_uoms u
                 where u.product_id = v_product and u.uom_id = v_base and u.factor_to_base = 1 and u.is_active)
     or not exists (select 1 from public.tbl_inv_product_uoms u
                    where u.product_id = v_product and u.uom_id = v_purchase and u.is_active)
     or exists (select 1 from public.tbl_inv_product_uoms u
                where u.product_id = v_product and u.uom_id <> v_base and u.factor_to_base = 1 and u.is_active) then
    raise exception 'INV_MASTER: product % needs an active base UOM row with factor 1, an active purchase UOM row, and no other factor-1 row (D-106)', v_product
      using errcode = 'P0001';
  end if;
  return null;
end $$;

create or replace function public.fn_inv_guard_barcodes() returns trigger
language plpgsql set search_path = '' as $$
begin
  if tg_op = 'UPDATE' and (new.barcode <> old.barcode or new.product_id <> old.product_id or new.uom_id <> old.uom_id) then
    raise exception 'INV_MASTER: a barcode row cannot be re-pointed; deactivate it and add a new one (D-128)'
      using errcode = 'P0001';
  end if;
  select p.owner_branch_id into new.owner_branch_id from public.tbl_inv_products p where p.id = new.product_id;
  return new;
end $$;

create or replace function public.fn_inv_guard_suppliers() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.owner_branch_id is not null
     and not exists (select 1 from public.tbl_branches b where b."BranchID" = new.owner_branch_id and b.is_demo) then
    raise exception 'INV_MASTER: owner_branch_id must be NULL or a demo branch (D-102)' using errcode = 'P0001';
  end if;
  if tg_op = 'UPDATE' and new.owner_branch_id is distinct from old.owner_branch_id then
    raise exception 'INV_MASTER: owner_branch_id cannot change' using errcode = 'P0001';
  end if;
  return new;
end $$;

-- D-135/D-140: only NUR branches have inventory settings and locations.
create or replace function public.fn_inv_guard_nur_branch() returns trigger
language plpgsql set search_path = '' as $$
begin
  if not exists (select 1 from public.tbl_branches b where b."BranchID" = new.branch_id and b."Function" = 'NUR') then
    raise exception 'INV_MASTER: inventory is only for NUR branches (D-135)' using errcode = 'P0001';
  end if;
  -- jsonb, not new.kind: this function serves two tables with different columns
  if tg_op = 'UPDATE' and (to_jsonb(new)->'branch_id' <> to_jsonb(old)->'branch_id'
                           or to_jsonb(new)->'kind' is distinct from to_jsonb(old)->'kind') then
    raise exception 'INV_MASTER: a location/settings row cannot change branch or kind' using errcode = 'P0001';
  end if;
  return new;
end $$;

create or replace function public.fn_inv_guard_stock_levels() returns trigger
language plpgsql set search_path = '' as $$
declare
  v_kind text;
begin
  select l.branch_id, l.kind into new.branch_id, v_kind from public.tbl_inv_locations l where l.id = new.location_id;
  if v_kind is null or v_kind not in ('STORE','FLOOR') then
    raise exception 'INV_MASTER: max levels exist only for STORE and FLOOR (D-24)' using errcode = 'P0001';
  end if;
  if not exists (select 1 from public.tbl_inv_products p where p.id = new.product_id and p.is_stock_item
                 and (p.owner_branch_id is null or p.owner_branch_id = new.branch_id)) then
    raise exception 'INV_MASTER: max level product must be a stock item visible to the branch' using errcode = 'P0001';
  end if;
  return new;
end $$;

create or replace function public.fn_inv_guard_resident_billing() returns trigger
language plpgsql set search_path = '' as $$
begin
  select r.branch_id into new.branch_id from public.tbl_residents r where r.id = new.resident_id;
  return new;
end $$;

-- ----------------------------------------------------------------------------
-- 10. Attach the triggers (drop + create so the file can be re-run)
-- ----------------------------------------------------------------------------
do $$
declare
  t text;
  v_append_only text[] := array['tbl_inv_txns','tbl_inv_txn_lines','tbl_inv_charges','tbl_inv_charge_exports',
    'tbl_inv_charge_export_items','tbl_inv_audit_log','tbl_inv_idempotency','tbl_inv_receipt_lines',
    'tbl_inv_branch_transfer_lines','tbl_inv_branch_transfer_receipts','tbl_inv_stock_request_events',
    'tbl_inv_period_closing'];
  v_documents text[] := array['tbl_inv_receipts','tbl_inv_branch_transfers','tbl_inv_billing_periods',
    'tbl_inv_stock_requests','tbl_inv_stock_request_lines','tbl_inv_counts','tbl_inv_count_lines',
    'tbl_inv_adjustments','tbl_inv_adjustment_lines'];
  v_caches text[] := array['tbl_inv_cost_pools','tbl_inv_balances','tbl_inv_counters'];
  v_master text[] := array['tbl_inv_uoms','tbl_inv_categories','tbl_inv_suppliers','tbl_inv_products',
    'tbl_inv_product_uoms','tbl_inv_product_barcodes','tbl_inv_branch_settings','tbl_inv_locations',
    'tbl_inv_stock_levels','tbl_inv_resident_billing'];
begin
  foreach t in array v_append_only loop
    execute format('drop trigger if exists trg_inv_immutable on public.%I', t);
    execute format('create trigger trg_inv_immutable before update or delete on public.%I
                    for each row execute function public.fn_inv_block_mutation()', t);
  end loop;
  foreach t in array v_documents loop
    execute format('drop trigger if exists trg_inv_document on public.%I', t);
    execute format('create trigger trg_inv_document before update or delete on public.%I
                    for each row execute function public.fn_inv_guard_document()', t);
  end loop;
  foreach t in array v_caches loop
    execute format('drop trigger if exists trg_inv_cache on public.%I', t);
    execute format('create trigger trg_inv_cache before insert or update or delete on public.%I
                    for each row execute function public.fn_inv_guard_cache()', t);
  end loop;
  foreach t in array v_master loop
    execute format('drop trigger if exists trg_inv_no_delete on public.%I', t);
    execute format('create trigger trg_inv_no_delete before delete on public.%I
                    for each row execute function public.fn_inv_block_delete()', t);
  end loop;
  foreach t in array v_append_only || v_documents || v_caches || v_master loop
    execute format('drop trigger if exists trg_inv_no_truncate on public.%I', t);
    execute format('create trigger trg_inv_no_truncate before truncate on public.%I
                    for each statement execute function public.fn_inv_block_truncate()', t);
  end loop;
end $$;

drop trigger if exists trg_inv_products_guard on public.tbl_inv_products;
create trigger trg_inv_products_guard before insert or update on public.tbl_inv_products
  for each row execute function public.fn_inv_guard_products();

drop trigger if exists trg_inv_products_uom_check on public.tbl_inv_products;
create constraint trigger trg_inv_products_uom_check after insert or update on public.tbl_inv_products
  deferrable initially deferred for each row execute function public.fn_inv_check_product_uoms();

drop trigger if exists trg_inv_product_uoms_guard on public.tbl_inv_product_uoms;
create trigger trg_inv_product_uoms_guard before update on public.tbl_inv_product_uoms
  for each row execute function public.fn_inv_guard_product_uoms();

drop trigger if exists trg_inv_product_uoms_check on public.tbl_inv_product_uoms;
create constraint trigger trg_inv_product_uoms_check after insert or update on public.tbl_inv_product_uoms
  deferrable initially deferred for each row execute function public.fn_inv_check_product_uoms();

drop trigger if exists trg_inv_barcodes_guard on public.tbl_inv_product_barcodes;
create trigger trg_inv_barcodes_guard before insert or update on public.tbl_inv_product_barcodes
  for each row execute function public.fn_inv_guard_barcodes();

drop trigger if exists trg_inv_suppliers_guard on public.tbl_inv_suppliers;
create trigger trg_inv_suppliers_guard before insert or update on public.tbl_inv_suppliers
  for each row execute function public.fn_inv_guard_suppliers();

drop trigger if exists trg_inv_locations_guard on public.tbl_inv_locations;
create trigger trg_inv_locations_guard before insert or update on public.tbl_inv_locations
  for each row execute function public.fn_inv_guard_nur_branch();

drop trigger if exists trg_inv_settings_guard on public.tbl_inv_branch_settings;
create trigger trg_inv_settings_guard before insert or update on public.tbl_inv_branch_settings
  for each row execute function public.fn_inv_guard_nur_branch();

drop trigger if exists trg_inv_stock_levels_guard on public.tbl_inv_stock_levels;
create trigger trg_inv_stock_levels_guard before insert or update on public.tbl_inv_stock_levels
  for each row execute function public.fn_inv_guard_stock_levels();

drop trigger if exists trg_inv_resident_billing_guard on public.tbl_inv_resident_billing;
create trigger trg_inv_resident_billing_guard before insert or update on public.tbl_inv_resident_billing
  for each row execute function public.fn_inv_guard_resident_billing();

-- ============================================================================
-- 11. Lock everything down before this transaction commits (audit V-1)
-- ============================================================================
-- The live default ACL gives anon/authenticated ALL on every new table and
-- EXECUTE on every new function, and PostgREST sees new objects at once. So
-- every inventory file ends by calling fn_inv_lockdown(): RLS on for every
-- tbl_inv_* table and NO privilege for PUBLIC, anon, authenticated or
-- service_role on any inventory table, view, sequence or function. Nothing is
-- reachable through the API until 013_inventory_grants.sql grants exactly what
-- is intended. Each file is therefore safe on its own, even if the next file
-- is never applied. (Re-running any file revokes the API grants again until
-- 013 is re-run: fail closed.)
create or replace function public.fn_inv_lockdown()
returns void language plpgsql set search_path = '' as $$
declare
  r record;
begin
  for r in
    select c.relname, c.relkind from pg_catalog.pg_class c
      join pg_catalog.pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'public' and c.relkind in ('r','v','m','S')
       and (c.relname like 'tbl\_inv\_%' or c.relname like 'v\_inv\_%')
  loop
    if r.relkind = 'r' then
      execute format('alter table public.%I enable row level security', r.relname);
    end if;
    if r.relkind = 'S' then
      execute format('revoke all on sequence public.%I from public, anon, authenticated, service_role', r.relname);
    else
      execute format('revoke all on table public.%I from public, anon, authenticated, service_role', r.relname);
    end if;
  end loop;
  for r in
    select p.oid::regprocedure as sig from pg_catalog.pg_proc p
      join pg_catalog.pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and (p.proname like 'fn\_inv\_%' or p.proname like 'inv\_%')
  loop
    execute format('revoke all on function %s from public, anon, authenticated, service_role', r.sig);
  end loop;
end $$;

select public.fn_inv_lockdown();

commit;
