-- Migration: Index tbl_vital.entry_timestamp for all-residents / all-branches reads
--
-- What this does: adds one index on tbl_vital(entry_timestamp desc). No data
-- change, no other schema change, idempotent (IF NOT EXISTS).
--
-- Why: the Vital Signs tab reads tbl_vital with
--   ORDER BY entry_timestamp DESC LIMIT 500
-- and, for an HQ login, no selective branch filter. The two existing indexes
-- (idx_vital_branch, idx_vital_resident) lead on branch_id / resident_id, so
-- neither can serve that ORDER BY: Postgres falls back to a sequential scan
-- plus a top-N sort. This index turns that into a bounded index scan.
--
-- Measured effect, not a fix for anything: on the live database the unfiltered
-- read went from ~775ms (seq scan of 37,886 rows + heapsort) to an index scan.
-- That is a real but modest win on a sub-second query.
--
-- NOT a fix for "canceling statement due to statement timeout" on the
-- Vital Signs tab. An earlier version of this file claimed it was. That claim
-- was wrong: the read completes in well under a second, far below any
-- statement timeout, and the sibling Nursing Chart read returns its 500 rows
-- without trouble. The "All Residents" timeout is still unrooted -- see
-- docs/clinical.md. Do not cite this migration as its fix.

create index if not exists idx_vital_timestamp on tbl_vital (entry_timestamp desc);