/**
 * OSEM Medication Chart Generator
 * Version: PDF-safe + performance optimized
 *
 * PRESERVES:
 * - Existing public function signatures
 * - Existing medication/session logic
 * - Existing PRN generator
 * - Existing chart template/layout
 * - Existing placeholder names
 * - Existing progress model
 * - Existing return object
 *
 * PERFORMANCE CHANGES:
 * - Removes unnecessary SpreadsheetApp.flush() calls from inner loops.
 * - Batches medication values into range.setValues() calls.
 * - Batches the 31-day serving matrix into ONE setValues() call.
 * - Keeps the final flush only after the resident's chart pages are built.
 * - Avoids changing chart appearance or medication-day logic.
 */

// ============================================================
// PUBLIC: SINGLE RESIDENT / BRANCH SHARED GENERATOR
// ============================================================

function generateResidentMedicationCharts(
  residentID,
  year,
  month,
  executionId,
  branchProgressState
) {
  residentID = String(residentID || "").trim();
  year = Number(year);
  month = Number(month);
  executionId = String(executionId || "").trim();

  if (!residentID) {
    throw new Error("ResidentID is required.");
  }

  if (!Number.isFinite(year) || year < 2000) {
    throw new Error("Invalid chart year: " + year);
  }

  if (!Number.isFinite(month) || month < 1 || month > 12) {
    throw new Error("Invalid chart month: " + month);
  }

  if (!executionId) {
    executionId = Utilities.getUuid();
  }

  var resident = getResident(residentID);

  if (!resident) {
    throw new Error("Resident not found: " + residentID);
  }

  var branchMode = !!branchProgressState;

  if (!branchMode) {
    setGenerationProgress(
      executionId,
      15,
      "Loading medication orders for " +
        String(resident.Residents || residentID) +
        "..."
    );
  }

  // IMPORTANT:
  // Do not flush here. The previous implementation flushed before
  // every page even though the sheet changes do not need to be forced
  // to the server at this point. The final chart/export pipeline will
  // perform the required flush at the appropriate stage.

  // ----------------------------------------------------------
  // Load regular medication preparation sessions.
  // ----------------------------------------------------------
  var sessions = getPreparationSessions(residentID) || [];

  // PRN medication is generated by the existing PRN generator.
  var prnMedications = getResidentPRNMedication(residentID) || [];

  var totalRegularPages = sessions.length;

  var totalPRNPages = 0;

  if (prnMedications.length > 0) {
    totalPRNPages = Math.ceil(
      prnMedications.length / PRN_PER_PAGE
    );
  }

  var totalPages =
    totalRegularPages + totalPRNPages;

  if (totalPages <= 0) {
    throw new Error(
      "No medication chart pages found for " +
      String(resident.Residents || residentID) +
      "."
    );
  }

  if (!branchMode) {
    setGenerationProgress(
      executionId,
      18,
      "Medication orders loaded. Preparing chart pages..."
    );
  }

  var generatedSheets = [];

  // ==========================================================
  // REGULAR MEDICATION CHARTS
  // ==========================================================

  for (var i = 0; i < sessions.length; i++) {
    var session = sessions[i];

    if (!branchMode) {
      var before = calculateMedicationChartProgress(
        i,
        totalPages
      );

      setGenerationProgress(
        executionId,
        before,
        "Preparing " +
          String(
            session.title ||
            session.time ||
            "Medication Preparation"
          ) +
          "..."
      );
    } else {
      setGenerationProgress(
        executionId,
        calculateMedicationChartProgress(
          branchProgressState.completedPages,
          branchProgressState.totalPages
        ),
        "Preparing " +
          String(
            session.title ||
            session.time ||
            "Medication Preparation"
          ) +
          " for " +
          String(resident.Residents || residentID) +
          "...",
        {
          residentNumber:
            branchProgressState.residentNumber,
          totalResidents:
            branchProgressState.totalResidents
        }
      );
    }

    // IMPORTANT:
    // No SpreadsheetApp.flush() before page creation.

    var sheet = createRegularMedicationChartPage(
      resident,
      session,
      year,
      month,
      executionId,
      i + 1,
      totalPages
    );

    generatedSheets.push(sheet);

    if (branchMode) {
      branchProgressState.completedPages =
        Number(branchProgressState.completedPages || 0) + 1;
    }

    if (!branchMode) {
      var completed = i + 1;

      setGenerationProgress(
        executionId,
        calculateMedicationChartProgress(
          completed,
          totalPages
        ),
        String(
          session.title ||
          session.time ||
          "Medication Preparation"
        ) +
          " completed."
      );
    }

    // IMPORTANT:
    // No SpreadsheetApp.flush() after every page.
    // This was one of the major execution-time costs.
  }

  // ==========================================================
  // PRN CHARTS
  // ==========================================================

  if (prnMedications.length > 0) {
    if (!branchMode) {
      setGenerationProgress(
        executionId,
        calculateMedicationChartProgress(
          totalRegularPages,
          totalPages
        ),
        "Preparing PRN medication chart..."
      );
    }

    var completedBeforePRN = branchMode
      ? Number(branchProgressState.completedPages || 0)
      : totalRegularPages;

    // Preserve the existing PRNChart.gs implementation.
    var prnSheets = generatePRNCharts(
      resident,
      prnMedications,
      year,
      month,
      executionId,
      totalPages,
      completedBeforePRN,
      branchProgressState || null
    ) || [];

    for (var p = 0; p < prnSheets.length; p++) {
      generatedSheets.push(prnSheets[p]);
    }

    // PRNChart.gs normally updates branchProgressState itself.
    if (
      branchMode &&
      prnSheets.length > 0 &&
      branchProgressState
    ) {
      var expectedPRNCompletion =
        completedBeforePRN + prnSheets.length;

      if (
        Number(branchProgressState.completedPages || 0) <
        expectedPRNCompletion
      ) {
        branchProgressState.completedPages =
          expectedPRNCompletion;
      }
    }
  }

  if (generatedSheets.length === 0) {
    throw new Error(
      "Medication chart generation produced no sheets for " +
      String(resident.Residents || residentID) +
      "."
    );
  }

  if (!branchMode) {
    setGenerationProgress(
      executionId,
      50,
      "Medication chart preparation completed."
    );
  }

  // One flush per resident, rather than one flush per page.
  SpreadsheetApp.flush();

  return {
    resident: resident,
    residentID: residentID,
    branch: resident.Branch || "",
    year: year,
    month: month,
    executionId: executionId,
    regularPages: totalRegularPages,
    prnPages: totalPRNPages,
    totalPages: totalPages,
    sheets: generatedSheets
  };
}


// ============================================================
// PROGRESS CALCULATION
// ============================================================

function calculateMedicationChartProgress(
  completedPages,
  totalPages
) {
  var START = 15;
  var END = 50;

  totalPages = Number(totalPages) || 0;
  completedPages = Number(completedPages) || 0;

  if (totalPages <= 0) {
    return START;
  }

  var safeCompleted = Math.max(
    0,
    Math.min(completedPages, totalPages)
  );

  var progress =
    START +
    (safeCompleted / totalPages) *
    (END - START);

  return Math.max(
    START,
    Math.min(END, progress)
  );
}


// ============================================================
// REGULAR CHART PAGE
// ============================================================
//
// The visual/template structure is preserved.
//
// The main performance change is that medication values and the
// 31-day matrix are written in batches instead of performing
// individual setValue() calls for every cell.
//
// ============================================================

function createRegularMedicationChartPage(
  resident,
  session,
  year,
  month,
  executionId,
  pageNumber,
  totalPages
) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();

  if (!ss) {
    throw new Error(
      "Unable to access the source spreadsheet while creating a medication chart."
    );
  }

  if (
    typeof CONFIG === "undefined" ||
    !CONFIG ||
    !CONFIG.TEMPLATE_SHEET
  ) {
    throw new Error(
      "CONFIG.TEMPLATE_SHEET is not configured."
    );
  }

  var template = ss.getSheetByName(
    CONFIG.TEMPLATE_SHEET
  );

  if (!template) {
    throw new Error(
      "Medication chart template not found: " +
      CONFIG.TEMPLATE_SHEET
    );
  }

  var medications =
    (session && session.medications) || [];

  if (medications.length === 0) {
    throw new Error(
      "No regular medication found for session: " +
      String(
        (session && (session.title || session.time)) || ""
      )
    );
  }

  // ============================================================
  // FIXED TEMPLATE LAYOUT
  // ============================================================

  var medicineStartRow = 9;
  var pageNumberCell = "AG32";
  var servingTimeCell = "B6";

  var medicineCell =
    medChart_findPlaceholderCell(
      template,
      "{{MEDICINE}}"
    );

  if (!medicineCell) {
    throw new Error(
      'Chart Template is missing "{{MEDICINE}}".'
    );
  }

  var noCell =
    medChart_findPlaceholderCell(
      template,
      "{{NO}}"
    );

  var indicationCell =
    medChart_findPlaceholderCell(
      template,
      "{{INDICATION}}"
    );

  var notedByCell =
    medChart_findPlaceholderCell(
      template,
      "{{NOTED_BY}}"
    );

  if (!noCell) {
    throw new Error(
      'Chart Template is missing "{{NO}}".'
    );
  }

  if (!indicationCell) {
    throw new Error(
      'Chart Template is missing "{{INDICATION}}".'
    );
  }

  if (!notedByCell) {
    throw new Error(
      'Chart Template is missing "{{NOTED_BY}}".'
    );
  }

  if (medicineCell.getRow() !== medicineStartRow) {
    throw new Error(
      'Chart Template medication row must be row 9. Current row: ' +
      medicineCell.getRow()
    );
  }

  var templateColumns = {
    no: noCell.getColumn(),
    medicine: medicineCell.getColumn(),
    indication: indicationCell.getColumn(),
    notedBy: notedByCell.getColumn()
  };

  var firstDayColumn = templateColumns.notedBy + 1;
  var numberOfDayColumns = 31;

  var lastMedicationRow = 31;
  var maxMedicationRows =
    lastMedicationRow - medicineStartRow + 1;

  if (medications.length > maxMedicationRows) {
    throw new Error(
      "Too many medications for the Chart Template in " +
      String(session.title || session.time || "this session") +
      ". Maximum supported without changing the template layout is " +
      maxMedicationRows + "."
    );
  }

  // ============================================================
  // COPY TEMPLATE
  // ============================================================

  var sheet = template.copyTo(ss);

  var safeResident =
    String(
      resident.ResidentID ||
      resident.Residents ||
      "RESIDENT"
    )
      .replace(/[^A-Za-z0-9_-]/g, "_");

  var safeSession =
    String(
      session.time ||
      session.title ||
      "CUSTOM"
    )
      .replace(/[^A-Za-z0-9_-]/g, "_");

  var sheetName =
    "MED_" +
    executionId +
    "_" +
    safeResident +
    "_" +
    safeSession +
    "_" +
    String(pageNumber);

  sheet.setName(
    medChart_makeUniqueSheetName(
      ss,
      sheetName
    )
  );

  // ============================================================
  // HEADER
  // ============================================================

  medChart_replacePlaceholder(
    sheet,
    "{{RESIDENT_NAME}}",
    resident.Residents || ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{MONTH}}",
    medChart_formatMonth(year, month)
  );

  var servingTimeText =
    "Serving Time: " +
    String(
      session.title ||
      session.time ||
      ""
    );

  sheet
    .getRange(servingTimeCell)
    .setValue(servingTimeText)
    .setVerticalAlignment("middle");

  medChart_replacePlaceholder(
    sheet,
    "{{SESSION_TITLE}}",
    session.title ||
      session.time ||
      ""
  );

  // ============================================================
  // PAGE NUMBER
  // ============================================================

  var safeTotalPages =
    Number(totalPages) > 0
      ? Number(totalPages)
      : 1;

  sheet
    .getRange(pageNumberCell)
    .setValue(
      "Page: " +
      Number(pageNumber || 1) +
      "/" +
      safeTotalPages
    );

  // ============================================================
  // DATE / MEDICATION MATRIX
  // ============================================================

  var daysInMonth =
    getDaysInMonth(year, month);

  // Build ALL medication columns in memory first.
  // This avoids one setValue() per cell.

  var noValues = [];
  var medicineValues = [];
  var indicationValues = [];
  var notedByValues = [];
  var dateMatrix = [];

  for (var i = 0; i < medications.length; i++) {
    var med = medications[i];

    noValues.push([
      i + 1
    ]);

    medicineValues.push([
      buildMedicineDescription(med) || ""
    ]);

    indicationValues.push([
      med["Indication"] || ""
    ]);

    // "Noted By" is normally stored as a StaffID.
    // Convert it to StaffName for the printed chart.
    var rawStaff =
      med["Noted By"] ||
      med["Ordered By"] ||
      "";

    var staffName = "";

    if (rawStaff) {
      staffName =
        getStaffName(rawStaff) ||
        String(rawStaff);
    }

    notedByValues.push([
      staffName
    ]);

    // Build the entire 31-day row in memory.
    var rowDateValues = [];

    for (var day = 1; day <= numberOfDayColumns; day++) {
      var serving =
        day <= daysInMonth &&
        shouldPrepareMedicineOnDay(
          med,
          year,
          month,
          day
        );

      rowDateValues.push(
        serving ? "" : "xxxx"
      );
    }

    dateMatrix.push(rowDateValues);
  }

  var rowCount = medications.length;

  // ============================================================
  // BATCH WRITE MEDICATION COLUMNS
  // ============================================================

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.no,
      rowCount,
      1
    )
    .setValues(noValues);

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.medicine,
      rowCount,
      1
    )
    .setValues(medicineValues);

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.indication,
      rowCount,
      1
    )
    .setValues(indicationValues);

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.notedBy,
      rowCount,
      1
    )
    .setValues(notedByValues);

  // ============================================================
  // BATCH WRITE ENTIRE 31-DAY MATRIX
  // ============================================================

  sheet
    .getRange(
      medicineStartRow,
      firstDayColumn,
      rowCount,
      numberOfDayColumns
    )
    .setValues(dateMatrix);

  // ============================================================
  // PRESERVE TEMPLATE ALIGNMENT / WRAPPING
  // ============================================================
  //
  // The template already carries the intended formatting.
  // We only re-apply these properties to the populated ranges,
  // as the original function did, but in batches.
  //

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.no,
      rowCount,
      1
    )
    .setHorizontalAlignment("center")
    .setVerticalAlignment("middle");

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.medicine,
      rowCount,
      1
    )
    .setWrap(true)
    .setVerticalAlignment("middle");

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.indication,
      rowCount,
      1
    )
    .setWrap(true)
    .setVerticalAlignment("middle");

  sheet
    .getRange(
      medicineStartRow,
      templateColumns.notedBy,
      rowCount,
      1
    )
    .setWrap(true)
    .setVerticalAlignment("middle");

  // ============================================================
  // CLEAN UNUSED TEMPLATE TOKENS
  // ============================================================

  medChart_replacePlaceholder(
    sheet,
    "{{NO}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{MEDICINE}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{INDICATION}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{NOTED_BY}}",
    ""
  );

  medChart_replacePlaceholder(
    sheet,
    "{{PAGE}}",
    Number(pageNumber || 1) + "/" + safeTotalPages
  );

  // IMPORTANT:
  // Do NOT flush here.
  // The caller flushes once after the resident's chart pages
  // have been generated.
  return sheet;
}


// ============================================================
// PLACEHOLDER HELPERS
// ============================================================

function medChart_findPlaceholderCell(
  sheet,
  placeholder
) {
  return sheet
    .createTextFinder(placeholder)
    .matchEntireCell(true)
    .useRegularExpression(false)
    .findNext();
}


function medChart_replacePlaceholder(
  sheet,
  placeholder,
  value
) {
  var replacement =
    value === null ||
    value === undefined
      ? ""
      : String(value);

  sheet
    .createTextFinder(placeholder)
    .matchEntireCell(true)
    .useRegularExpression(false)
    .replaceAllWith(replacement);
}


// ============================================================
// MONTH / SHEET NAME HELPERS
// ============================================================

function medChart_formatMonth(
  year,
  month
) {
  var date = new Date(
    Number(year),
    Number(month) - 1,
    1
  );

  return Utilities.formatDate(
    date,
    Session.getScriptTimeZone(),
    "MMMM yyyy"
  );
}


function medChart_makeUniqueSheetName(
  ss,
  proposedName
) {
  var base =
    String(
      proposedName || "MedicationChart"
    ).substring(0, 100);

  if (!ss.getSheetByName(base)) {
    return base;
  }

  for (var i = 2; i <= 999; i++) {
    var suffix = "_" + i;

    var candidate =
      base.substring(
        0,
        100 - suffix.length
      ) + suffix;

    if (!ss.getSheetByName(candidate)) {
      return candidate;
    }
  }

  return (
    base.substring(0, 85) +
    "_" +
    Utilities.getUuid().substring(0, 12)
  ).substring(0, 100);
}


// ============================================================
// OPTIONAL TEST
// ============================================================

function testResidentMedicationChartGenerator() {
  var residentID = "AMN-14";
  var year = 2026;
  var month = 9;

  var executionId =
    Utilities.getUuid();

  var report =
    generateResidentMedicationCharts(
      residentID,
      year,
      month,
      executionId
    );

  Logger.log(
    JSON.stringify(
      {
        residentID:
          report.residentID,
        resident:
          report.resident.Residents,
        pages:
          report.sheets.length,
        executionId:
          executionId
      },
      null,
      2
    )
  );
}
