import { NextRequest, NextResponse } from "next/server";
import { renderToBuffer } from "@react-pdf/renderer";
import { getServerTranslator } from "@/lib/i18n/server";
import { getInventoryContext } from "@/lib/inventory/server";
import { loadReport } from "@/lib/inventory/reports";
import { parseReportParams } from "@/lib/inventory/reports/params";
import { CSV_ROW_CAP, PDF_ROW_CAP, REPORTS, isReportKey } from "@/lib/inventory/reports/types";
import { buildReportCsv, reportFileName } from "@/lib/inventory/csv";
import { getReportBranchInfo } from "@/lib/pdf/branch-info";
import { getLogoPath } from "@/lib/pdf/logo-path";
import { formatDateTime } from "@/lib/format-date";
import { InventoryReportDocument } from "@/lib/pdf/documents/inventory-report-document";
import { todayKL } from "@/lib/inventory/core";

export const runtime = "nodejs";

// Inventory report exports (Phase 7, docs/inventory-design.md section 15):
// /api/inventory/reports/<report>?format=csv|pdf&branch=..&<the page's filters>.
// The report name and every parameter are validated against whitelists, the
// rank is checked here as well as on the page, and every read goes through
// the caller's own Supabase session (RLS scopes branches and DEMO), so this
// route can never return more than the page would show.

const NO_STORE = { "Cache-Control": "no-store" };

function fail(code: string, status: number) {
  return NextResponse.json({ ok: false, code }, { status, headers: NO_STORE });
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ report: string }> }) {
  const { report } = await params;
  if (!isReportKey(report)) return fail("UNKNOWN_REPORT", 404);
  const def = REPORTS[report];

  const search = request.nextUrl.searchParams;
  const format = search.get("format");
  if (format !== "csv" && format !== "pdf") return fail("INVALID_FORMAT", 400);

  const ctx = await getInventoryContext(search.get("branch") ?? undefined);
  if (!ctx) return fail("NOT_AUTHENTICATED", 401);
  if (ctx.branchId === null || ctx.rank < def.minRank) return fail("FORBIDDEN", 403);

  const parsed = parseReportParams(Object.fromEntries(search.entries()), def.filters);
  if (parsed.error) return fail(parsed.error, 400);

  const { t } = await getServerTranslator();
  const cap = format === "pdf" ? PDF_ROW_CAP : CSV_ROW_CAP;
  const result = await loadReport(report, { sb: ctx.supabase, branchId: ctx.branchId, rank: ctx.rank, t, cap, params: parsed.params });
  if (result.error) return fail(result.error, 500);

  const branchLabel = ctx.branches.find((b) => b.id === ctx.branchId)?.label ?? String(ctx.branchId);
  const day = todayKL();

  if (format === "csv") {
    const body = buildReportCsv(result.columns, result.rows, result.totals);
    return new Response(body, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${reportFileName(report, branchLabel, day, "csv")}"`,
        "X-Content-Type-Options": "nosniff",
        "X-Export-Rows": String(result.rows.length),
        "X-Export-Truncated": result.truncated ? "1" : "0",
        ...NO_STORE,
      },
    });
  }

  const branch = await getReportBranchInfo(ctx.branchId);
  const buffer = await renderToBuffer(
    <InventoryReportDocument
      report={result}
      branch={branch}
      logoSrc={getLogoPath()}
      generatedBy={ctx.account.username}
      generatedAt={formatDateTime(new Date().toISOString())}
      labels={{ generatedBy: t("Generated by"), generatedAt: t("Generated at"), noRows: t("No rows for these filters.") }}
      truncationNote={result.truncated ? t("Only the first {count} rows are shown. Narrow the filters to see the rest.", { count: cap }) : null}
    />
  );
  return new NextResponse(buffer as unknown as BodyInit, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${reportFileName(report, branchLabel, day, "pdf")}"`,
      "X-Content-Type-Options": "nosniff",
      ...NO_STORE,
    },
  });
}
