export type Resident = {
  id: number;
  branch_id: number;
  resident_name: string;
  ic_number: string | null;
  age: number | null;
  nationality_id: number | null;
  gender: "M" | "F" | null;
  marital_status: string | null;
  status: "ACTIVE" | "DISCHARGED" | "DECEASED" | "TRANSFERRED OUT";
  category: string | null;
  care_type: string | null;
  admission_date: string | null;
  discharge_date: string | null;
  transfer_from: string | null;
  accompanied_by: string | null;
  emergency_contact: string | null;
  allergy: string | null;
  past_medical_condition: string | null;
  medication_reconciliation_log: string | null;
  current_medication_list: string | null;
  mobility: string | null;
  feeding_type_id: number | null;
  hygiene: string | null;
  diet_type_id: number | null;
  care_goal: string[] | null;
  tca_notes: string | null;
  assessment_and_summary: string | null;
  reviewed_by: string | null;  // tbl_staff.StaffID, e.g. "AMN-1"
  reviewed_by_other: string | null;
};

export type Staff = {
  // "<BranchCode>-<running number>", e.g. "AMN-1" -- generated by a DB
  // trigger on insert, not app-assigned.
  StaffID: string;
  branch_id: number;
  staff_name: string;
  position_id: number;
  role: "ADMIN" | "MODERATOR" | "STAFF";
  department: "Nursing" | "Medical" | "Physiotherapy";
  status: "ACTIVE" | "INACTIVE";
};

export type ProgressNote = {
  id: number;
  branch_id: number;
  resident_id: number;
  entry_timestamp: string;
  progress_note: string | null;
  physical_examination: string | null;
  medical_plan: string | null;
  monitoring_plan: string | null;
  feeding_plan: string | null;
  dressing_plan: string | null;
  nursing_plan: string | null;
  physio_plan: string | null;
  reviewed_by: string | null;  // tbl_staff.StaffID, e.g. "AMN-1"
  created_by: string | null;
};

export type PhysioAssessment = {
  id: number;
  branch_id: number;
  resident_id: number;
  entry_timestamp: string;
  treatment_type: string | null;
  credit_hours: number | null;
  chief_complaint: string | null;
  current_history: string | null;
  past_medical_history: string | null;
  social_history: string | null;
  impression: string | null;
  plan_intervention: string | null;
  evaluation: string | null;
  treatment_compliance: string | null;
  total_score: number | null;
  documented_by: string | null;  // tbl_staff.StaffID, e.g. "AMN-1"
};

export type PhysioExamination = {
  id: number;
  assessment_id: number;
  limb: "lower" | "upper";
  region: string;
  movement: string;
  side: "R" | "L";
  power: number | null;
  tone: number | null;
  rom: number | null;
  reflexes: number | null;
};

export type PhysioBodyChartFinding = {
  id: number;
  assessment_id: number;
  region: string;
  side: "R" | "L" | null;
  comment: string;
};

export type PhysioFunctionalAssessment = {
  id: number;
  assessment_id: number;
  supine_to_side_lying: number | null;
  side_lying_to_sitting: number | null;
  sitting_to_standing: number | null;
  sit_at_edge_of_bed: number | null;
  ambulation: number | null;
};

export type PhysioBalanceAssessment = {
  id: number;
  assessment_id: number;
  sitting_static: number | null;
  sitting_dynamic: number | null;
  standing_static: number | null;
  standing_dynamic: number | null;
};

export type PhysioCoordinationAssessment = {
  id: number;
  assessment_id: number;
  upper_limb_right: number | null;
  upper_limb_left: number | null;
  lower_limb_right: number | null;
  lower_limb_left: number | null;
};

export const PHYSIO_COMPLIANCE_OPTIONS = ["100%", "75%", "50%", "25%"] as const;

export type UserAccount = {
  id: number;
  email: string;
  username: string;
  branch_id: number;
  rights: "ADMIN" | "MODERATOR" | "STAFF";
  status: "ACTIVE" | "INACTIVE";
};

// id is string for staff (tbl_staff's PK is a text code, e.g. "AMN-1"),
// number for every other lookup (positions, branches, etc.).
export type LookupOption = { id: number | string; label: string };

export const GENDER_OPTIONS = ["M", "F"] as const;
export const MARITAL_STATUS_OPTIONS = ["Single", "Married", "Windowed", "Divorced"] as const;
export const RESIDENT_STATUS_OPTIONS = ["ACTIVE", "DISCHARGED", "DECEASED", "TRANSFERRED OUT"] as const;
export const CARE_TYPE_OPTIONS = ["24-Hour Care", "Daycare"] as const;
export const TRANSFER_FROM_OPTIONS = ["Home", "Hospital", "Nursing Home", "Others"] as const;
export const ACCOMPANIED_BY_OPTIONS = ["Self", "Family", "Friends", "Social Worker", "Paramedic", "Others"] as const;
export const MOBILITY_OPTIONS = ["Walking Independent", "Walking Aid", "Wheelchair", "Bedbound"] as const;
export const HYGIENE_OPTIONS = ["Self Toileting", "Urinal", "Bedpan", "Commode Chair", "Pampers"] as const;
export const CARE_GOAL_OPTIONS = ["Nursing/ADL care", "Rehabilitation", "Wound Care", "Paliative Care", "Others"] as const;
// tbl_vital.spo2_condition / .dxt_remark check constraints -- shared between
// the Vitals "Record Vital Signs" form and the Hospital Referral form, both
// of which require the matching condition/remark whenever the reading itself
// is entered.
export const SPO2_CONDITION_OPTIONS = [
  "under RA",
  "under 1LPM O2",
  "under 2LPM O2",
  "under 3LPM O2",
  "under 4LPM O2",
  "under 5LPM O2",
  "under 6LPM O2",
  "under 7LPM O2",
  "under 8LPM O2",
  "under 9LPM O2",
  "under 10LPM O2",
] as const;
export const DXT_REMARK_OPTIONS = ["Fasting", "Post-Meal 1hr", "Post-Meal 2hr", "Post-Meal >4hr"] as const;
// tbl_staff.role -- coarse category used to scope role-restricted
// staff-picker dropdowns (see getStaffRoster/getAllStaffWithBranch in
// lib/lookups.ts). Separate enum from id_rights even though the labels
// now match -- see schema notes.
export const STAFF_ROLE_OPTIONS = ["ADMIN", "MODERATOR", "STAFF"] as const;
export const DEPARTMENT_OPTIONS = ["Nursing", "Medical", "Physiotherapy"] as const;
export const STAFF_STATUS_OPTIONS = ["ACTIVE", "INACTIVE"] as const;
// tbl_user_accounts.rights -- login access level. Deliberately just 3 tiers,
// unrelated to tbl_staff.role.
export const RIGHTS_OPTIONS = ["ADMIN", "MODERATOR", "STAFF"] as const;
